version: 2
jobs:
  build:
    docker:
      - image: zhaofengshu33/mini-latex:v1

    steps:
      - checkout

      - run:
          name: build
          command: make
      - store_artifacts:
          path: ./build/iconip_2019.pdf
          destination: iconip_2019.pdf